### ISSUE TITLE
Link at readme is leading to 404

### ISSUE THREAD

**Issue by leomotta121** [Foxhunt/convos.art#30]
Hey the url on your read me is leading to a 404 page! Thx

**Comment by Foxhunt** [comment]
Hi can you post the Link?

There is no Link in the [readme](https://github.com/Foxhunt/convos.art/blob/master/README.md)

**Comment by leomotta121** [comment]
Sorry, I should have provided it for you.

https://github.com/Foxhunt/convos.art/tree/6db3f8d1d4b98295edf104c463a1ae9bb16a4806
